name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16, 18]


    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js and pnpm
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # - run: npm ci
    # - run: npm run build --if-present
    - run: npm i  
    - run: npm test
